import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Card from "~/components/Card";
import FloatingIconMenu from "~/components/widgets/FloatingIconMenu";
import SquareMenuGrid from "~/components/widgets/SquareMenuGrid";

import { Announce } from "~/types/Annouce";
import Notification from "~/components/widgets/Notification";
import ProfileModal from "~/components/Profile/ProfileModal";

const Home: NextPage = () => {
  const { data: annouceData } = api.announce.getAll.useQuery<Announce>();

  return (
    <>
      <Head>
        <title>- yXa - Residential Portal </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-12">
          <div className="col-span-8">
            {annouceData?.map((item) => (
              <Card key={item.id} {...item} />
            ))}
          </div>
          <div className="col-span-4">
            <FloatingIconMenu />

            <SquareMenuGrid />
            {/* <Notification text="We are using cookies for no reason." /> */}
          </div>
        </div>
      </div>

      {/* for profile model window */}
      <ProfileModal />
    </>
  );
};

export default Home;
